name: AmidstUs
main: me.jakubmeysner.amidstus.AmidstUs
version: ${version}
description: Spigot plugin which allows you to play Among Us in Minecraft.
api-version: 1.16
website: https://github.com/jakubmeysner/amidstus

commands:
  createmap:
    description: Creates a new map.
    permission: amidstus.maps.create
    usage: /createmap <name>
  renamemap:
    description: Renames a map.
    permission: amidstus.maps.rename
    usage: /renamemap <name> <new name>
  deletemap:
    description: Deletes a map.
    permission: amidstus.maps.delete
    usage: /deletemap <name>
  setmapdisplayname:
    description: Sets map's display name.
    permission: amidstus.maps.setdisplayname
    usage: /setmapdisplayname <name> <display name>
  maps:
    description: Lists maps.
    permission: amidstus.maps.list
    usage: /maps
  map:
    description: Displays details concerning a map.
    permission: amidstus.maps.details
    usage: /map <name>
  setmappostloc:
    description: Sets map's post game location.
    permission: amidstus.maps.locations.post
    usage: /setmappostloc <name>
  loadmaps:
    description: Loads maps from file.
    permission: amidstus.maps.load
    usage: /loadmaps
  savemaps:
    description: Saves maps to file.
    permission: amidstus.maps.save
    usage: /savemaps
  setmappreloc:
    description: Sets map's pre game location.
    permission: amidstus.maps.locations.pre
    usage: /setmappreloc <name>
  play:
    description: Quick play in a public game.
    permission: amidstus.games.use.play.public
    usage: /join [map name]
  creategame:
    description: Creates a new private game.
    permission: amidstus.games.use.play.private
    usage: /creategame <map name>
  leavegame:
    description: Leaves your current game.
    permission: amidstus.games.use.leave
    usage: /leavegame
  invite:
    description: Invites a player to a private game.
    permission: amidstus.games.use.invite.send
    usage: /invite <player>
  acceptinvite:
    description: Accepts invite from the specified player.
    permission: amidstus.games.use.invite.respond
    usage: /acceptinvite <player>
  denyinvite:
    description: Denies invite from the specified player.
    permission: amidstus.games.use.invite.respond
    usage: /denyinvite <player>
  addmapvent:
    description: Adds a new vent to map.
    permission: amidstus.maps.vents
    usage: /addmapvent <map name>
  removemapvent:
    description: Removes existing vent from map.
    permission: amidstus.maps.vents
    usage: /removemapvent <map name> <vent id>
  linkmapvents:
    description: Links existing vents on map.
    permission: amidstus.maps.vents
    usage: /linkmapvents <map name> <vent one id> <vent two id>
  mapvents:
    description: Lists vents with their coordinates on given map.
    permission: amidstus.maps.vents
    usage: /mapvents <map name>

permissions:
  amidstus.*:
    description: Gives you complete access.
    children:
      amidstus.maps.*: true
      amidstus.games.*: true
  amidstus.maps.*:
    description: Gives you access to map management.
    children:
      amidstus.maps.create: true
      amidstus.maps.rename: true
      amidstus.maps.delete: true
      amidstus.maps.setdisplayname: true
      amidstus.maps.load: true
      amidstus.maps.save: true
      amidstus.maps.locations.*: true
  amidstus.maps.create:
    description: Allows you to create new maps.
  amidstus.maps.rename:
    description: Allows you to rename maps.
  amidstus.maps.delete:
    description: Allows you to delete maps.
  amidstus.maps.setdisplayname:
    description: Allows you to set maps' display names.
  amidstus.maps.list:
    description: Allows you to list maps.
    default: true
  amidstus.maps.details:
    description: Allows you to display details concerning a map.
    default: true
  amidstus.maps.locations.*:
    description: Gives you access to maps locations management.
    children:
      amidstus.maps.locations.post: true
      amidstus.maps.locations.pre: true
  amidstus.maps.locations.post:
    description: Allows you to set maps' post game locations.
  amidstus.maps.load:
    description: Allows you to load maps from file.
  amidstus.maps.save:
    description: Allows you to save maps to file.
  amidstus.maps.locations.pre:
    description: Allows you to set maps' pre game locations.
  amidstus.games.*:
    description: Gives you complete access to games.
    children:
      amidstus.games.use.*: true
  amidstus.games.use.*:
    description: Gives you access to gameplay.
    default: true
    children:
      amidstus.games.use.play.*: true
      amidstus.games.use.leave: true
      amidstus.games.use.invite: true
  amidstus.games.use.play.*:
    description: Allows you to join and create games.
    children:
      amidstus.games.use.play.public: true
  amidstus.games.use.play.public:
    description: Allows you to join and create public games.
  amidstus.games.use.play.private:
    description: Allows you to join and create private games.
  amidstus.games.use.leave:
    description: Allows you to leave games.
  amidstus.games.use.invite.*:
    description: Gives you access to game invites.
    children:
      amidstus.games.use.invite.send: true
      amidstus.games.use.invite.respond: true
  amidstus.games.use.invite.send:
    description: Allows you to send invites to games.
  amidstus.games.use.invite.respond:
    description: Allows you to respond to game invites.
