name: AmidstUs
main: me.jakubmeysner.amidstus.AmidstUs
version: ${version}
description: Spigot plugin which allows you to play Among Us in Minecraft.
api-version: 1.16
website: https://github.com/jakubmeysner/amidstus

commands:
  createmap:
    description: Creates a new map.
    permission: amidstus.maps.manage
    usage: /createmap <map name>
  renamemap:
    description: Renames a map.
    permission: amidstus.maps.manage
    usage: /renamemap <map name> <new map name>
  deletemap:
    description: Deletes a map.
    permission: amidstus.maps.manage
    usage: /deletemap <map name>
  setmapdisplayname:
    description: Sets map's display name.
    permission: amidstus.maps.manage
    usage: /setmapdisplayname <map name> <map display name>
  maps:
    description: Lists maps.
    permission: amidstus.maps.info
    usage: /maps
  map:
    description: Displays details concerning a map.
    permission: amidstus.maps.info
    usage: /map <map name>
  setmappostloc:
    description: Sets map's post game location.
    permission: amidstus.maps.manage
    usage: /setmappostloc <map name>
  loadmaps:
    description: Loads maps from file.
    permission: amidstus.maps.saving
    usage: /loadmaps
  savemaps:
    description: Saves maps to file.
    permission: amidstus.maps.saving
    usage: /savemaps
  setmappreloc:
    description: Sets map's pre game location.
    permission: amidstus.maps.manage
    usage: /setmappreloc <map name>
  play:
    description: Quick play in a public game.
    permission: amidstus.games.play.public
    usage: /play [map name]
  creategame:
    description: Creates a new private game.
    permission: amidstus.games.play.private
    usage: /creategame <map name>
  leavegame:
    description: Leaves your current game.
    permission: amidstus.games.play.common
    usage: /leavegame
  invite:
    description: Invites a player to a private game.
    permission: amidstus.games.play.private
    usage: /invite <player name>
  acceptinvite:
    description: Accepts invite from the specified player.
    permission: amidstus.games.play.private
    usage: /acceptinvite <player name>
  denyinvite:
    description: Denies invite from the specified player.
    permission: amidstus.games.play.private
    usage: /denyinvite <player name>
  setmapminplayers:
    description: Sets map's min number of players.
    permission: amidstus.maps.manage
    usage: /setmapminplayers <map name> <number>
  setmapmaxplayers:
    description: Sets map's max number of players.
    permission: amidstus.maps.manage
    usage: /setmapmaxplayers <map name> <number>
  setmapmaximpostors:
    description: Sets map's max number of impostors.
    permission: amidstus.maps.manage
    usage: /setmapmaximpostors <map name> <number>
  addmapseat:
    description: Adds a new seat to map.
    permission: amidstus.maps.manage
    usage: /addmapseat <map name>
  removemapseat:
    description: Removes a seat from map.
    permission: amidstus.maps.manage
    usage: /removemapseat <map name> <index>
  mapseats:
    description: Lists maps' seats.
    permission: amidstus.maps.info
    usage: /mapseats <map name>
  setmapautostartplayers:
    description: Sets map's auto start number of players.
    permission: amidstus.maps.manage
    usage: /setmapautostartplayers <map name> <number>
  switchmap:
    description: Switches game map to specified map.
    permission: amidstus.games.play.private
    usage: /switchmap <map name>
  startgame:
    description: Starts the game.
    permission: amidstus.games.play.private
    usage: /startgame

permissions:
  amidstus.*:
    description: Gives you full access.
  amidstus.maps.*:
    description: Gives you access to maps.
    children:
      amidstus.maps.info: true
      amidstus.maps.manage: true
      amidstus.maps.saving: true
  amidstus.maps.info:
    description: Allows you to display information about maps.
    default: true
  amidstus.maps.manage:
    description: Allows you to manage maps.
  amidstus.maps.saving:
    description: Allows you to load and save maps.
  amidstus.games.*:
    description: Gives you access to games.
    children:
      amidstus.games.play: true
  amidstus.games.play.*:
    description: Allows you to play games.
    default: true
    children:
      amidstus.games.play.public: true
      amidstus.games.play.private: true
      amidstus.games.play.common: true
  amidstus.games.play.public:
    description: Allows you to join public games.
  amidstus.games.play.private:
    description: Allows you to create and join private games.
  amidstus.games.play.common:
    description: Allows you to play games.
